"""
app/reports/templates/advisory.py
Consumer Advisory PDF — for fraud score 21-39.
Soft language, no legal citations, buyer beware tone.
"""

from reportlab.platypus import Paragraph, Spacer, HRFlowable
from reportlab.lib.units import cm
from reportlab.lib.colors import HexColor

from app.reports.pdf_builder import (
    get_styles, section_header, fraud_score_table,
    COLOR_WARNING, COLOR_PRIMARY, COLOR_DARK_GRAY
)


def build_advisory(report: dict, user_info: dict) -> list:
    """Returns list of flowable elements for advisory PDF."""
    styles = get_styles()
    elements = []
    fraud = report.get("fraud_score", {})
    extraction = report.get("layer_results", {}).get("math_validation", {})
    product = report.get("product_name", "Unknown Product")
    score = fraud.get("score", 0)
    signals = fraud.get("signals", [])

    # Header
    elements.append(Paragraph("NutriGuard AI", styles["title"]))
    elements.append(Paragraph("Consumer Product Advisory", styles["subtitle"]))
    elements.append(Paragraph(
        f"Generated on: {user_info.get('date', 'Today')}",
        styles["subtitle"]
    ))
    elements.append(Spacer(1, 0.4*cm))
    elements.append(HRFlowable(width="100%", thickness=1, color=COLOR_PRIMARY))
    elements.append(Spacer(1, 0.3*cm))

    # Fraud Score
    elements.append(fraud_score_table(score, fraud.get("level", ""), styles))
    elements.append(Spacer(1, 0.4*cm))

    # Product Info
    elements.append(section_header("PRODUCT INFORMATION", COLOR_PRIMARY, styles))
    elements.append(Spacer(1, 0.2*cm))
    elements.append(Paragraph(f"<b>Product:</b> {product}", styles["body"]))
    elements.append(Paragraph(
        f"<b>Purchased From:</b> {user_info.get('store', 'Not specified')}",
        styles["body"]
    ))
    elements.append(Paragraph(
        f"<b>Date of Purchase:</b> {user_info.get('purchase_date', 'Not specified')}",
        styles["body"]
    ))
    elements.append(Spacer(1, 0.3*cm))

    # Advisory Notice
    elements.append(section_header("ADVISORY NOTICE", COLOR_WARNING, styles))
    elements.append(Spacer(1, 0.2*cm))
    elements.append(Paragraph(
        f"NutriGuard AI has analysed the nutritional claims on <b>{product}</b> "
        f"and found minor concerns that consumers should be aware of before purchase. "
        f"While this product does not appear to contain critically fraudulent claims, "
        f"some labelling practices may not fully represent the product's nutritional profile.",
        styles["body"]
    ))
    elements.append(Spacer(1, 0.3*cm))

    # Issues Found
    elements.append(section_header("CONCERNS IDENTIFIED", COLOR_WARNING, styles))
    elements.append(Spacer(1, 0.2*cm))
    for i, signal in enumerate(signals, 1):
        elements.append(Paragraph(
            f"<b>{i}. {signal.get('signal', '')}",
            styles["body_bold"]
        ))
        for detail in signal.get("details", []):
            elements.append(Paragraph(f"• {detail}", styles["body"]))
        elements.append(Spacer(1, 0.2*cm))

    # Recommendation
    elements.append(section_header("RECOMMENDATION", COLOR_PRIMARY, styles))
    elements.append(Spacer(1, 0.2*cm))
    elements.append(Paragraph(
        "This product has minor labelling concerns. We recommend consumers "
        "read the full nutrition label carefully before purchase. No formal "
        "complaint is required at this time.",
        styles["body"]
    ))
    elements.append(Spacer(1, 0.5*cm))
    elements.append(HRFlowable(width="100%", thickness=0.5, color=COLOR_DARK_GRAY))
    elements.append(Spacer(1, 0.2*cm))
    elements.append(Paragraph(
        "Generated by NutriGuard AI | Automated Nutritional Fraud Detection System",
        styles["small"]
    ))

    return elements